[package]
name = "appmgr"
version = "0.2.7"
authors = ["Aiden McClelland <me@drbonez.dev>"]
edition = "2018"

[lib]
name = "appmgrlib"
path = "src/lib.rs"

[[bin]]
name = "appmgr"
path = "src/main.rs"

[features]
default = []
portable = []
production = []

[dependencies]
emver = { git = "https://github.com/Start9Labs/emver-rs.git", version = "0.1.0", features = ["serde"] }
argonautica = "0.2.0"
async-trait = "0.1.41"
base32 = "0.4.0"
clap = "2.33"
ed25519-dalek = "1.0.1"
failure = "0.1.8"
file-lock = "1.1"
futures = "0.3.7"
git-version = "0.3.4"
itertools = "0.9.0"
lazy_static = "1.4"
linear-map = { version = "1.2", features = ["serde_impl"] }
log = "0.4.11"
openssl = "0.10.30"
pest = "2.1"
pest_derive = "2.1"
prettytable-rs = "0.8.0"
rand = "0.7.3"
regex = "1.4.2"
reqwest = { version = "0.10.8", features = ["stream", "json"] }
rpassword = "5.0.0"
serde = { version = "1.0.117", features = ["derive", "rc"] }
serde_yaml = "0.8.14"
serde_cbor = "0.11.1"
serde_json = "1.0.59"
simple-logging = "2.0"
tokio = { version = "0.2.22", features = ["full"] }
tokio-tar = "0.2.0"
